name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: gitmodle
      run: git submodule update --init
    - name: gitmodle2
      run: git -C thirdparty/boost update --init  
    - name: configure
      run: ./build/premake.sh
    - name: make
      run: make -f benchmark.make config=release_x64 && make -f nativejson.make config=release_x64
    - name: make check
      run: ./build/machine.sh
    - name: make distcheck
      run: make distcheck
