name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Version
      # You may pin to the exact commit or the version.
      # uses: codacy/git-version@fa06788276d7492a2af01662649696d249ecf4cb
      uses: actions/checkout@v3
    - uses: actions/checkout@v3
    - name: gitmodle
      run: git submodule update --init
      # - uses: codacy/git-version@2.4.0
      # - name: gitmodle2
      #  run: cd thirdparty/boost  && git  update --init  
    - name: configure
      run: ./build/premake.sh
    - name: make
      run: make -f benchmark.make config=release_x64 && make -f nativejson.make config=release_x64
    - name: make check
      run: ./build/machine.sh
    - name: make distcheck
      run: make distcheck
